logging:
  file: application.log
  level:
    de.angelasensio.morningstar: DEBUG
    org: ERROR
    yahoofinance: OFF
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger - %msg%n){yellow}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger - %msg%n"